# Generated by Django 4.2.7 on 2023-12-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='best',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='лучшие фильмы'),
        ),
        migrations.AddField(
            model_name='actor',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='actor',
            name='filmcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего фильмов'),
        ),
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='director',
            name='best',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='лучшие фильмы'),
        ),
        migrations.AddField(
            model_name='director',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='director',
            name='filmcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего фильмов'),
        ),
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Фото'),
        ),
    ]
