# Generated by Django 4.2.7 on 2023-12-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_actor_best_actor_data_actor_filmcount_actor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kino',
            name='trailer',
            field=models.URLField(blank=True, null=True, verbose_name='Трейлер'),
        ),
    ]
